# -*- coding: utf-8 -*-
"""Portfolio Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rrjs0Vcam9D-P-lKQo9b7sk6Fro_sVE
"""

"""
Modern Portfolio Theory (MPT) Calculator
==========================================
Diversified across: Stocks, Bonds, REITs, Index ETFs, Commodities

All 5 bugs from the original code are fixed:
  Bug 1 — results_df now properly created after the simulation loop
  Bug 2 — best_idx and best_weights now properly defined
  Bug 3 — VFIAX (mutual fund, not on yfinance) replaced with VOO (ETF)
  Bug 4 — Dirichlet sampling used for unbiased simplex weights
  Bug 5 — mean and covariance both annualised before use
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# ── 1. ASSET UNIVERSE ───────────────────────────────────────────────────────
tickers = [
    'AAPL', 'MSFT', 'AMZN',   # Stocks
    'BND',  'TLT',             # Bonds (ETFs)
    'VNQ',                     # REIT
    'VOO',  'SPY', 'QQQ',      # Index ETFs  (VOO replaces VFIAX)
    'GLD',  'USO',             # Commodities
]

ASSET_CLASS = {
    'AAPL': 'Stock', 'MSFT': 'Stock', 'AMZN': 'Stock',
    'BND':  'Bond',  'TLT':  'Bond',
    'VNQ':  'REIT',
    'VOO':  'Index', 'SPY':  'Index', 'QQQ':  'Index',
    'GLD':  'Commodity', 'USO': 'Commodity',
}

# ── 2. DOWNLOAD DATA ─────────────────────────────────────────────────────────
def download_data(tickers, start, end):
    try:
        import yfinance as yf
        print("Downloading price data from Yahoo Finance...")
        raw = yf.download(tickers, start=start, end=end,
                          auto_adjust=True, progress=False)
        if isinstance(raw.columns, pd.MultiIndex):
            data = raw["Close"]
        else:
            data = raw
        data = data.dropna()
        if data.empty:
            raise ValueError("No data returned — check your internet connection.")
        print(f"  {len(data)} trading days loaded for {len(data.columns)} assets.\n")
        return data
    except Exception as e:
        print(f"  Download failed ({e}). Using built-in sample data.\n")
        return None

# ── 3. BUILT-IN SAMPLE DATA (realistic 2018-2024 approximate stats) ──────────
def make_sample_data():
    """
    Generates synthetic daily returns that match approximate real-world
    annualised returns and volatilities for each asset, with realistic
    cross-correlations.  Used only when Yahoo Finance is unavailable.
    """
    np.random.seed(0)
    n_days = 1500

    # Approximate annual stats (return, volatility)
    stats = {
        'AAPL': (0.28, 0.30), 'MSFT': (0.25, 0.27), 'AMZN': (0.20, 0.35),
        'BND':  (0.03, 0.05), 'TLT':  (0.01, 0.14),
        'VNQ':  (0.08, 0.20),
        'VOO':  (0.14, 0.18), 'SPY':  (0.14, 0.18), 'QQQ':  (0.18, 0.22),
        'GLD':  (0.07, 0.14), 'USO':  (0.02, 0.45),
    }

    # Simple correlation structure (equity block + bond block + commodities)
    n = len(tickers)
    corr = np.eye(n)
    for i in range(n):
        for j in range(n):
            ti, tj = tickers[i], tickers[j]
            ci, cj = ASSET_CLASS[ti], ASSET_CLASS[tj]
            if i == j:
                corr[i, j] = 1.0
            elif ci == cj == 'Stock':
                corr[i, j] = 0.75
            elif ci == cj == 'Index':
                corr[i, j] = 0.97
            elif ci in ('Stock', 'Index') and cj in ('Stock', 'Index'):
                corr[i, j] = 0.80
            elif ci == cj == 'Bond':
                corr[i, j] = 0.70
            elif ci in ('Stock', 'Index') and cj == 'Bond':
                corr[i, j] = -0.20
            elif ci == 'REIT' and cj in ('Stock', 'Index'):
                corr[i, j] = 0.60
            elif ci == 'Commodity' and cj == 'Bond':
                corr[i, j] = -0.10
            else:
                corr[i, j] = 0.10
            corr[j, i] = corr[i, j]

    daily_means = np.array([stats[t][0] / 252 for t in tickers])
    daily_vols  = np.array([stats[t][1] / np.sqrt(252) for t in tickers])

    # Build covariance from correlation + vols
    D    = np.diag(daily_vols)
    cov  = D @ corr @ D

    # Ensure positive-definiteness via eigenvalue floor
    eigvals, eigvecs = np.linalg.eigh(cov)
    eigvals = np.maximum(eigvals, 1e-8)
    cov = eigvecs @ np.diag(eigvals) @ eigvecs.T

    # Cholesky to generate correlated returns
    L    = np.linalg.cholesky(cov)
    z    = np.random.randn(n_days, n)
    rets = z @ L.T + daily_means

    idx  = pd.date_range("2018-01-02", periods=n_days, freq='B')
    return pd.DataFrame(rets, index=idx, columns=tickers)

# ── 4. LOAD DATA ─────────────────────────────────────────────────────────────
data = download_data(tickers, "2018-01-01", "2024-12-31")

if data is not None:
    returns     = data.pct_change().dropna()
else:
    print("Using synthetic sample data (realistic approximation).")
    returns     = make_sample_data()

# ── 5. ANNUALISED STATISTICS ─────────────────────────────────────────────────
mean_annual = returns.mean() * 252        # Bug 5 fix: annualise before use
cov_annual  = returns.cov()  * 252        # Bug 5 fix: annualise before use
n           = len(tickers)
RISK_FREE   = 0.03                        # 3% annual risk-free rate

# ── 6. MONTE CARLO SIMULATION ────────────────────────────────────────────────
num_portfolios = 100_000
np.random.seed(42)

results        = np.zeros((3, num_portfolios))
weights_record = []

print(f"Simulating {num_portfolios:,} random portfolios...")
for i in range(num_portfolios):
    # Bug 4 fix: Dirichlet → uniform distribution over the simplex
    weights = np.random.dirichlet(np.ones(n))
    weights_record.append(weights)

    port_return     = np.dot(weights, mean_annual)
    port_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_annual, weights)))
    sharpe_ratio    = (port_return - RISK_FREE) / port_volatility

    results[0, i] = port_return
    results[1, i] = port_volatility
    results[2, i] = sharpe_ratio

# ── 7. BUILD DATAFRAME AND FIND OPTIMAL PORTFOLIOS ───────────────────────────
# Bug 1 fix: results_df created here
results_df = pd.DataFrame(results.T, columns=['Return', 'Volatility', 'Sharpe'])

# Bug 2 fix: best_idx and best_weights defined here
best_idx       = results_df['Sharpe'].idxmax()
min_vol_idx    = results_df['Volatility'].idxmin()

best_weights   = pd.Series(weights_record[best_idx],    index=tickers)
minvol_weights = pd.Series(weights_record[min_vol_idx], index=tickers)

# Efficient frontier envelope
sorted_df          = results_df.sort_values('Volatility')
efficient_frontier = sorted_df['Return'].cummax()

# ── 8. PRINT RESULTS ─────────────────────────────────────────────────────────
def print_portfolio(label, weights_series, row):
    print(f"\n{'='*55}")
    print(f"  {label}")
    print(f"{'='*55}")
    print(f"  Expected Annual Return : {row['Return']:.2%}")
    print(f"  Annual Volatility      : {row['Volatility']:.2%}")
    print(f"  Sharpe Ratio           : {row['Sharpe']:.4f}")
    print(f"\n  Weights:")
    for ticker, w in weights_series.sort_values(ascending=False).items():
        bar = '█' * int(w * 40)
        cls = ASSET_CLASS.get(ticker, '')
        print(f"    {ticker:<6}  {w*100:6.2f}%  {bar}  [{cls}]")

print_portfolio("★  MAX SHARPE RATIO PORTFOLIO",
                best_weights,   results_df.loc[best_idx])
print_portfolio("●  MIN VOLATILITY PORTFOLIO",
                minvol_weights, results_df.loc[min_vol_idx])

# ── 9. PLOTS ──────────────────────────────────────────────────────────────────
print("\nGenerating charts...")
fig, axes = plt.subplots(1, 3, figsize=(19, 6))
fig.suptitle("Modern Portfolio Theory — Diversified Portfolio\n"
             "Stocks | Bonds | REITs | Index ETFs | Commodities",
             fontsize=14, fontweight='bold')

CLASS_COLOR = {
    'Stock': '#4F8EF7', 'Bond': '#2ECC71', 'REIT': '#E67E22',
    'Index': '#9B59B6', 'Commodity': '#F1C40F',
}

# — Efficient Frontier ——————————————————————————————————————
ax1 = axes[0]
sc  = ax1.scatter(results_df['Volatility'], results_df['Return'],
                  c=results_df['Sharpe'], cmap='viridis', s=1.5, alpha=0.45)
fig.colorbar(sc, ax=ax1, label='Sharpe Ratio', shrink=0.85)
ax1.plot(sorted_df['Volatility'], efficient_frontier,
         color='orange', linewidth=2.5, label='Efficient Frontier', zorder=3)
ax1.scatter(results_df.loc[best_idx,    'Volatility'],
            results_df.loc[best_idx,    'Return'],
            color='red',  marker='*', s=350, zorder=5,
            label=f"Max Sharpe  ({results_df.loc[best_idx,'Sharpe']:.2f})")
ax1.scatter(results_df.loc[min_vol_idx, 'Volatility'],
            results_df.loc[min_vol_idx, 'Return'],
            color='lime', marker='*', s=350, zorder=5,
            label=f"Min Vol  ({results_df.loc[min_vol_idx,'Volatility']:.2%})")
ax1.set_title("Efficient Frontier", fontweight='bold')
ax1.set_xlabel("Annual Volatility (Risk)")
ax1.set_ylabel("Expected Annual Return")
ax1.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{x:.0%}"))
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{x:.0%}"))
ax1.legend(fontsize=8)
ax1.grid(True, alpha=0.3)

# — Max Sharpe weights ——————————————————————————————————————
ax2 = axes[1]
top_sh  = best_weights.sort_values(ascending=False)
colors1 = [CLASS_COLOR.get(ASSET_CLASS[t], '#888') for t in top_sh.index]
bars1   = ax2.barh(top_sh.index, top_sh.values * 100,
                   color=colors1, edgecolor='white', linewidth=0.5)
ax2.bar_label(bars1, fmt='%.1f%%', padding=4, fontsize=9)
ax2.set_title("★  Max Sharpe Ratio\nPortfolio Weights", fontweight='bold')
ax2.set_xlabel("Allocation (%)")
ax2.invert_yaxis()
ax2.grid(True, axis='x', alpha=0.3)
ax2.set_xlim(0, top_sh.values.max() * 130)

# — Min Vol weights —————————————————————————————————————————
ax3 = axes[2]
top_mv  = minvol_weights.sort_values(ascending=False)
colors2 = [CLASS_COLOR.get(ASSET_CLASS[t], '#888') for t in top_mv.index]
bars2   = ax3.barh(top_mv.index, top_mv.values * 100,
                   color=colors2, edgecolor='white', linewidth=0.5)
ax3.bar_label(bars2, fmt='%.1f%%', padding=4, fontsize=9)
ax3.set_title("●  Min Volatility\nPortfolio Weights", fontweight='bold')
ax3.set_xlabel("Allocation (%)")
ax3.invert_yaxis()
ax3.grid(True, axis='x', alpha=0.3)
ax3.set_xlim(0, top_mv.values.max() * 130)

# Legend for asset classes
from matplotlib.patches import Patch
legend_patches = [Patch(facecolor=v, label=k) for k, v in CLASS_COLOR.items()]
fig.legend(handles=legend_patches, loc='lower center', ncol=5,
           fontsize=9, framealpha=0.9, bbox_to_anchor=(0.5, -0.04))

plt.tight_layout()
plt.savefig("efficient_frontier.png", dpi=150, bbox_inches='tight')
print("  Chart saved as: efficient_frontier.png")
print("\nDone!")